import React from 'react';

const Items = [
    {
      name: "Margherita Pizza",
      text: `Classic delight with 100% real mozzarella cheese. Available in Cheese Burst, Wheat Thin Crust, and Pan Crust options.`,
      img:`https://www.dominos.co.in/blog/wp-content/uploads/2019/12/A-Delicious-History-of-Your-Favourite-Classic-Margherita-Pizza.png`,
      price: `₹199`,
      veg: true,
      Pizza_Bases: `Whole Wheat Crust`,
      Pizza_Sauces: `Classic Marinara`,
      Cheese: "Mozzarella",
      Veggies: "none",
      meat: "none",
    },
    {
      name: "Fresh Veggie Pizza",
      text: `Delectable combination of onion & capsicum, a veggie lovers pick`,
      img:`https://cdn.dotpe.in/longtail/store-items/6385438/Cm1UDanF.jpeg`,
      price: `₹209`,
      veg: true,
      Pizza_Bases: `Thin Crust`,
      Pizza_Sauces: `White Alfredo Sauce`,
      Cheese: "Mozzarella",
      Veggies: `Capsicum`,
      meat: "none",
    },
    {
      name: "Cheese Overload",
      text: `Cheese Overloaded Pizza with a medley of Mozzarella, Cheddar & Ghost Pepper flavoured Cheese.`,
      img:`https://b.zmtcdn.com/data/dish_photos/773/fd7f927d5acf2244f17ec2a5b2512773.jpeg`,
      price: `₹349`,
      veg: true,
      Pizza_Bases: `Stuffed Crust`,
      Pizza_Sauces: `White Alfredo Sauce`,
      Cheese: "Cheddar",
      Veggies: 'Panner',
      meat: "none",
    },
    {
      name: "Veggie Buddies",
      text: `Best buddies Tomato and Capsicum come together on your Fav Crust with cheese & a no onion no garlic sauce`,
      img:`https://b.zmtcdn.com/data/dish_photos/72a/2a8ea479040d62f82871e1be7470672a.jpeg`,
      price: `₹209`,
      veg: true,
      Pizza_Bases: `Stuffed Crust`,
      Pizza_Sauces: `White Alfredo Sauce`,
      Cheese: "Mozzarella",
      Veggies: "Capsicum",
      meat: "none",
    },
    {
      name: "Mexican Green Wave Pizza",
      text: `Mexican herbs sprinkled on onion, capsicum, tomato & jalapeno`,
      img:`https://images.dominos.co.in/nextgen-catalog/media/prod/Dominos/HomeProductV1/46b4d899-40da-4c18-ad80-17f0775c2064_PIZ0178.jpg`,
      price: `₹269`,
      veg: true,
      Pizza_Bases: `Stuffed Crust`,
      Pizza_Sauces: `Spicy Sauce`,
      Cheese: "Cheddar",
      Veggies: 'Onion',
      meat: "none",
    },
    {
        name: "Peppy Paneer Pizza",
        text: `Flavorful trio of juicy paneer, crisp capsicum with spicy red paprika`,
        img:`https://images.dominos.co.in/nextgen-catalog/media/prod/Dominos/HomeProductV1/0d2dc3ea-f636-4ca5-a9a6-f746f4a5aae5_PIZ0179.jpg`,
        price: `₹269`,
        veg: true,
        Pizza_Bases: `Classic Hand-Tossed`,
        Pizza_Sauces: `White Alfredo Sauce`,
        Cheese: "Parmesan",
        Veggies: 'Panner',
        meat: "none",
      },
      {
        name: "Pepper Barbecue Chicken",
        text: `Pepper barbecue chicken for that extra zing`,
        img:`https://b.zmtcdn.com/data/dish_photos/829/7602a3d88b2aeb0053954d96be9a9829.jpeg`,
        price: `₹109`,
        veg: false,
        Pizza_Bases: `Stuffed Crust`,
        Pizza_Sauces: `Barbecue Sauce`,
        Cheese: "Cheddar",
        Veggies: "none",
        meat: "Chicken",
      },
      {
        name: "Non-Veg Supreme Pizza",
        text: `Supreme combination of black olives, onion, capsicum, grilled mushroom, pepper barbecue chicken, peri-peri chicken & grilled chicken rashers`,
        img:`https://images.dominos.co.in/nextgen-catalog/media/prod/Dominos/HomeProductV1/9ba34661-f787-4692-acf3-b0524e358a94_PIZ5148.jpg`,
        price: `₹369`,
        veg: false,
        Pizza_Bases: `Stuffed Crust`,
        Pizza_Sauces: `White Alfredo Sauce`,
        Cheese: "Cheddar",
        Veggies: "Capsicum" ,
        meat: "Chicken",
      }
   
  ];



export default Items;